### ISSUE TITLE
Add Unix socket support on windows

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#4208]
- [x] add [Unix sockets support on Windows](https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/) e40f0709
 - [x] add Linux [abstract socket](https://github.com/pocoproject/poco/commit/e40f07099d2e4d355d5048e44c039925f56ca694#diff-b9b98698fe6f5add22f6852d064c2aac723fb0122fbbabd85510b7bf24d48cfcR149) support e40f0709 (sadly [not working](https://github.com/microsoft/WSL/issues/4240) on windows, in spite of MS claiming [it does](https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/))
 - [ ] make C++17 default for VS2022 projects #4207 (needed to detect if `<afunix.h>` header is present)
 - [x] use localhost socket in PollSet on windows when available (mentioned in #3773 )
 
https://github.com/pocoproject/poco/issues/2770
