### ISSUE TITLE
Poco::Data fixes and improvements

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#4230]
- [x] transactions are not handled properly in `Poco::Data` (bug)
  - when `autoCommit` is off, currently the transaction behavior is not entirely correct; it should be as follows:
    - any statement (including `SELECT`) in non-autocommit mode should implicitly start a transaction
    - one or more statements executed in non-autocommit mode are not in effect until `commit()` or `rollback()` is executed on `Session`
  
  **Note: this is a breaking change that modifies the transaction semantics; eg. a  statement in a non-autocommit `Data::Session` will implicitly start a transaction (and lock rows) until commit or rollback is executed from outside.**

- [x] add `POCO::Data::SQLParser` (experimental, [sql-parser](https://github.com/hyrise/sql-parser) wrapper)
- [ ] #4365 (moved to separate issue)
- [x] add [MARS](https://learn.microsoft.com/en-us/previous-versions/sql/sql-server-2008/ms131686(v=sql.100)?redirectedfrom=MSDN) support
- [ ] #4366 (moved to separate issue)
  https://github.com/pocoproject/poco/blob/3da8ee633e0e028d530f282fe4ab6869de1e15b2/Data/include/Poco/Data/Session.h#L210

- [x] make `bool Poco::Data::Session::isTransaction()` return `Poco::Optional`
  Currently, in non-autocommit mode without explicit `Session::begin()`, we simply don't know whether we are in transaction or not and we have no control whether we effectively enter transaction or not - the DB will do it automatically in non-autocommit mode and our `Session` will not know it. To alleviate this situation, `SQLParser` will be added - not a 100% bulletproof solution, but better than nothing. In order to further minimize unpredictability, `bool Session::isTransaction()` should return `Poco::Optional`, so we are explicit about what we know; the downside of doing this is that it will break the code, but a major release is as good opportunity as it gets.

- [x] #4367 (moved to separate issue)
- [x] remove `SQLChannel::close()` parameter (hides virtual from parent)
- [x] move `SQLExecutor` to a library in `Poco::Data` testsuite, so it can be used by all back ends to achieve as much common behavior as possible/reasonable
  - [x] adjust `make` buildsystem
  - [x] adjust `CMake` buildsystem
  - [x] adjust `Visual Studio 2022` and `2019` projects (`SQLParser` needs C++17) cf. #4207 
- [x] #4368 (moved to separate issue)
- [x] fix MySQL failing native and ODBC tests @frwilckens 
- [x] fix My\\PostgreSQL failing native and ODBC tests @frwilckens 
- [ ] #4324
